# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.30
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_USER: missiria
      MYSQL_ROOT_PASSWORD: c++
      MYSQL_DATABASE: edge_recyclo
      MYSQL_PASSWORD: c++
      MYSQL_ALLOW_EMPTY_PASSWORD:
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  edge_recyclo:
