-- MySQL Script generated by MySQL Workbench
-- Sun 27 Feb 2022 10:31:13 +01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `society_id` VARCHAR(45) NULL,
  `fullname` VARCHAR(45) NULL,
  `gendre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(50) NOT NULL,
  `profession` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `phone` INT NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` FLOAT NULL,
  `country` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number_card` VARCHAR(45) NOT NULL,
  `expiry_year` VARCHAR(45) NOT NULL,
  `expiry_month` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `account_id` INT NOT NULL,
  `created_at` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_card_UNIQUE` (`number_card` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`collect` ;

CREATE TABLE IF NOT EXISTS `mydb`.`collect` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `collect_name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `point` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `collect_category_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `collect_category_id_idx` (`collect_category_id` ASC) VISIBLE,
  CONSTRAINT `collect_category_id`
    FOREIGN KEY (`collect_category_id`)
    REFERENCES `mydb`.`collect_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collect_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`collect_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`collect_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`declaration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`declaration` ;

CREATE TABLE IF NOT EXISTS `mydb`.`declaration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `collect_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `qt` FLOAT NOT NULL,
  `status` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `collect_id_idx` (`collect_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `collect_id`
    FOREIGN KEY (`collect_id`)
    REFERENCES `mydb`.`collect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`donation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL,
  `bank` VARCHAR(45) NULL,
  `rib` FLOAT NULL,
  `amount` FLOAT NULL,
  `account_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NOT NULL,
  `account_id` INT NOT NULL,
  `received_account_id` INT NOT NULL,
  `created_at` VARCHAR(45) GENERATED ALWAYS AS (CURRENT_TIMESTAMP),
  PRIMARY KEY (`id`),
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `received_account_id_idx` (`received_account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `received_account_id`
    FOREIGN KEY (`received_account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`point` ;

CREATE TABLE IF NOT EXISTS `mydb`.`point` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `point` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `account_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `account_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_review_1_idx` (`account_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`collect_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`withdrawal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`withdrawal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`withdrawal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
